import type { Metadata } from "next";
import {   Noto_Sans } from "next/font/google";
import "./globals.css";
import { ChilndProps } from '@/types'



const noto_sans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight:["100","200","300","400","500","600"]
});

export const metadata: Metadata = {
  title: "Turbo smm",
  description: "Generated by create next app",
};
  
 function RootLayout({children}: ChilndProps) {
  return (
    <html lang="en">
      <body
        className={` ${noto_sans.variable} overflow-x-hidden`}
      >
        {/* <Navbar/> */}
        {children}
      </body>
    </html>
  );
}

export default RootLayout;